### PR TITLE
Only make one request per identify call

### PR DESCRIPTION
**Pull request by sperand-io**
Alright, finally arrived at what I think is a solution to (both) potential sources of dupes.

Turns out sending the identify call at the same time as the add_to_list call not only can introduce race conditions but is also wholly redundant, because the add_to_list endpoint will update user properties (and accepts all the same standard and custom user properties as the identify endpoint) even if the user already exists and is a member of the list. If the user exists but is not a member of the list *and* has new properties, they'll first update the existing user with the new properties and then add them to the list. I've tested all sorts of combinations of the two endpoints in conjunction and it works seamlessly. 

Finally, sending anonymous user data to Klaviyo is only semi-supported and will result in potentially superfluous user profiles that you can't really act on. As such, we'll be introducing the *option* to send data pertaining to anonymous users and setting it as true for existing customers (non-breaking) but false for new ones going forward.

next steps:

- [x] review (logic and code :)
- [x] run migration to set `settings.sendAnonymous` to `true` for all Klaviyo integration instances
- [x] add `sendAnonymous` boolean option to Klaviyo meta doc w/ default value `false`
- [x] merge and deploy

@hankim813 @WesleyDRobinson @tsholmes

### CODE REVIEW

**Comment by hankim813** [comment]
@sperand-io LGTM! also you forgot:
- [ ] update `site-docs`

EDIT: well there's actually not much to update site-docs since metadata setting will auto populate the docs and there are no real other feature added.

**Review by tsholmes — APPROVED** [review]
🚢

**Comment by WesleyDRobinson** [comment]
Both integration code and tests look 💯 @sperand-io

**Comment by hankim813** [comment]
@sperand-io this is all taken care of -- feel free to notify partners

**Pull request merged**
